services:
  - type: web
    name: mizigox
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
