import type { RoleCode } from './enums.js';

export const PERMISSIONS = [
  'audit.read',
  'countries.manage',
  'countries.read',
  'customers.create',
  'customers.delete',
  'customers.manage',
  'customers.read',
  'customers.update',
  'dashboard.finance',
  'dashboard.operations',
  'dispatch.dispatch',
  'dispatch.manage',
  'dispatch.read',
  'documents.read',
  'driver_documents.create',
  'driver_documents.delete',
  'driver_documents.manage',
  'driver_documents.read',
  'driver_documents.update',
  'drivers.create',
  'drivers.delete',
  'drivers.manage',
  'drivers.read',
  'drivers.status_update',
  'drivers.update',
  'fleet.manage',
  'invoices.manage',
  'org.settings',
  'payments.record',
  'routes.create',
  'routes.delete',
  'routes.dispatch',
  'routes.manage',
  'routes.read',
  'routes.status_update',
  'routes.update',
  'routes.view_history',
  'shipments.assign',
  'shipments.create',
  'shipments.delete',
  'shipments.manage',
  'shipments.read',
  'shipments.update',
  'shipments.update_status',
  'shipments.upload_pod',
  'shipments.view_history',
  'tracking.update_location',
  'users.manage',
  'vehicle_documents.create',
  'vehicle_documents.delete',
  'vehicle_documents.manage',
  'vehicle_documents.read',
  'vehicle_documents.update',
  'vehicles.create',
  'vehicles.delete',
  'vehicles.manage',
  'vehicles.read',
  'vehicles.status_update',
  'vehicles.update',
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const ROLE_DEFINITIONS: Record<
  RoleCode,
  { name: string; description: string; scope: 'PLATFORM' | 'OPERATOR' | 'CUSTOMER' }
> = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    description: 'Full platform access across all tenants and configuration.',
    scope: 'PLATFORM',
  },
  OPERATIONS_ADMIN: {
    name: 'Operations Admin',
    description: 'Cross-operator operational access without payout administration.',
    scope: 'PLATFORM',
  },
  FINANCE_ADMIN: {
    name: 'Finance Admin',
    description: 'Cross-operator invoices, payments, and outstanding balances.',
    scope: 'PLATFORM',
  },
  COMPANY_ADMIN: {
    name: 'Company Admin',
    description: 'Administrator of a transport operator organization.',
    scope: 'OPERATOR',
  },
  LOGISTICS_MANAGER: {
    name: 'Logistics Manager',
    description: 'Shipments, fleet, drivers, routes, and assignment.',
    scope: 'OPERATOR',
  },
  FINANCE_OFFICER: {
    name: 'Finance Officer',
    description: 'Operator invoices, payments, and financial documents.',
    scope: 'OPERATOR',
  },
  DRIVER: {
    name: 'Driver',
    description: 'Assigned trips, status updates, proof of delivery, and location.',
    scope: 'OPERATOR',
  },
  CUSTOMER_ADMIN: {
    name: 'Customer Admin',
    description: 'Manages a customer organization, its users, and its freight.',
    scope: 'CUSTOMER',
  },
  CUSTOMER_USER: {
    name: 'Customer User',
    description: 'Creates and tracks shipments and views documents and invoices.',
    scope: 'CUSTOMER',
  },
};

export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  SUPER_ADMIN: PERMISSIONS,
  OPERATIONS_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'org.settings',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.manage',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
    'users.manage',
  ],
  FINANCE_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'dispatch.read',
    'documents.read',
    'driver_documents.read',
    'drivers.read',
    'invoices.manage',
    'payments.record',
    'routes.read',
    'routes.view_history',
    'shipments.read',
    'shipments.view_history',
    'vehicle_documents.read',
    'vehicles.read',
  ],
  COMPANY_ADMIN: [
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.finance',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'invoices.manage',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'org.settings',
    'payments.record',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.manage',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
    'users.manage',
  ],
  LOGISTICS_MANAGER: [
    'countries.read',
    'customers.create',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
  ],
  FINANCE_OFFICER: [
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'dispatch.read',
    'documents.read',
    'driver_documents.read',
    'drivers.read',
    'invoices.manage',
    'payments.record',
    'routes.read',
    'routes.view_history',
    'shipments.read',
    'shipments.view_history',
    'vehicle_documents.read',
    'vehicles.read',
  ],
  DRIVER: [
    'countries.read',
    'documents.read',
    'shipments.read',
    'shipments.update_status',
    'shipments.upload_pod',
    'shipments.view_history',
    'tracking.update_location',
  ],
  CUSTOMER_ADMIN: [
    'countries.read',
    'documents.read',
    'invoices.manage',
    'org.settings',
    'shipments.create',
    'shipments.read',
    'shipments.view_history',
    'users.manage',
  ],
  CUSTOMER_USER: [
    'countries.read',
    'documents.read',
    'shipments.create',
    'shipments.read',
    'shipments.view_history',
  ],
};
