import type { RoleCode } from './enums.js';

export const PERMISSIONS = [
  'audit.read',
  'countries.manage',
  'countries.read',
  'customers.create',
  'customers.delete',
  'customers.manage',
  'customers.read',
  'customers.update',
  'dashboard.finance',
  'dashboard.operations',
  'documents.read',
  'fleet.manage',
  'invoices.manage',
  'org.settings',
  'payments.record',
  'shipments.assign',
  'shipments.create',
  'shipments.read',
  'shipments.update',
  'shipments.update_status',
  'shipments.upload_pod',
  'tracking.update_location',
  'users.manage',
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const ROLE_DEFINITIONS: Record<
  RoleCode,
  { name: string; description: string; scope: 'PLATFORM' | 'OPERATOR' | 'CUSTOMER' }
> = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    description: 'Full platform access across all tenants and configuration.',
    scope: 'PLATFORM',
  },
  OPERATIONS_ADMIN: {
    name: 'Operations Admin',
    description: 'Cross-operator operational access without payout administration.',
    scope: 'PLATFORM',
  },
  FINANCE_ADMIN: {
    name: 'Finance Admin',
    description: 'Cross-operator invoices, payments, and outstanding balances.',
    scope: 'PLATFORM',
  },
  COMPANY_ADMIN: {
    name: 'Company Admin',
    description: 'Administrator of a transport operator organization.',
    scope: 'OPERATOR',
  },
  LOGISTICS_MANAGER: {
    name: 'Logistics Manager',
    description: 'Shipments, fleet, drivers, routes, and assignment.',
    scope: 'OPERATOR',
  },
  FINANCE_OFFICER: {
    name: 'Finance Officer',
    description: 'Operator invoices, payments, and financial documents.',
    scope: 'OPERATOR',
  },
  DRIVER: {
    name: 'Driver',
    description: 'Assigned trips, status updates, proof of delivery, and location.',
    scope: 'OPERATOR',
  },
  CUSTOMER_ADMIN: {
    name: 'Customer Admin',
    description: 'Manages a customer organization, its users, and its freight.',
    scope: 'CUSTOMER',
  },
  CUSTOMER_USER: {
    name: 'Customer User',
    description: 'Creates and tracks shipments and views documents and invoices.',
    scope: 'CUSTOMER',
  },
};

export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  SUPER_ADMIN: PERMISSIONS,
  OPERATIONS_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'documents.read',
    'fleet.manage',
    'org.settings',
    'shipments.assign',
    'shipments.create',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'users.manage',
  ],
  FINANCE_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'documents.read',
    'invoices.manage',
    'payments.record',
    'shipments.read',
  ],
  COMPANY_ADMIN: [
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.finance',
    'dashboard.operations',
    'documents.read',
    'fleet.manage',
    'invoices.manage',
    'org.settings',
    'payments.record',
    'shipments.assign',
    'shipments.create',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'users.manage',
  ],
  LOGISTICS_MANAGER: [
    'countries.read',
    'customers.create',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'documents.read',
    'fleet.manage',
    'shipments.assign',
    'shipments.create',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
  ],
  FINANCE_OFFICER: [
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'documents.read',
    'invoices.manage',
    'payments.record',
    'shipments.read',
  ],
  DRIVER: [
    'countries.read',
    'documents.read',
    'shipments.read',
    'shipments.update_status',
    'shipments.upload_pod',
    'tracking.update_location',
  ],
  CUSTOMER_ADMIN: [
    'countries.read',
    'documents.read',
    'invoices.manage',
    'org.settings',
    'shipments.create',
    'shipments.read',
    'users.manage',
  ],
  CUSTOMER_USER: ['countries.read', 'documents.read', 'shipments.create', 'shipments.read'],
};
