import type { RoleCode } from './enums.js';

export const PERMISSIONS = [
  'audit.read',
  'countries.manage',
  'countries.read',
  'customers.create',
  'customers.delete',
  'customers.manage',
  'customers.read',
  'customers.update',
  'dashboard.finance',
  'dashboard.operations',
  'dispatch.dispatch',
  'dispatch.manage',
  'dispatch.read',
  'documents.read',
  'driver_documents.create',
  'driver_documents.delete',
  'driver_documents.manage',
  'driver_documents.read',
  'driver_documents.update',
  'drivers.create',
  'drivers.delete',
  'drivers.manage',
  'drivers.read',
  'drivers.status_update',
  'drivers.update',
  'finance.manage',
  'finance.read',
  'fleet.manage',
  'invoices.cancel',
  'invoices.create',
  'invoices.issue',
  'invoices.manage',
  'invoices.read',
  'invoices.update',
  'notification_delivery.read',
  'notification_preferences.read',
  'notification_preferences.update',
  'notification_templates.manage',
  'notification_templates.read',
  'notifications.manage',
  'notifications.read',
  'notifications.retry',
  'org.settings',
  'payments.create',
  'payments.manage',
  'payments.read',
  'payments.record',
  'payments.refund',
  'payments.update',
  'pod.create',
  'pod.manage',
  'pod.read',
  'routes.create',
  'routes.delete',
  'routes.dispatch',
  'routes.manage',
  'routes.read',
  'routes.status_update',
  'routes.update',
  'routes.view_history',
  'search.read',
  'shipments.assign',
  'shipments.create',
  'shipments.delete',
  'shipments.manage',
  'shipments.read',
  'shipments.update',
  'shipments.update_status',
  'shipments.upload_pod',
  'shipments.view_history',
  'tracking.manage',
  'tracking.read',
  'tracking.submit_location',
  'tracking.update_location',
  'tracking.view_history',
  'tracking.view_live',
  'users.manage',
  'users.read',
  'vehicle_documents.create',
  'vehicle_documents.delete',
  'vehicle_documents.manage',
  'vehicle_documents.read',
  'vehicle_documents.update',
  'vehicles.create',
  'vehicles.delete',
  'vehicles.manage',
  'vehicles.read',
  'vehicles.status_update',
  'vehicles.update',
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const ROLE_DEFINITIONS: Record<
  RoleCode,
  { name: string; description: string; scope: 'PLATFORM' | 'OPERATOR' | 'CUSTOMER' }
> = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    description: 'Full platform access across all tenants and configuration.',
    scope: 'PLATFORM',
  },
  OPERATIONS_ADMIN: {
    name: 'Operations Admin',
    description: 'Cross-operator operational access without payout administration.',
    scope: 'PLATFORM',
  },
  FINANCE_ADMIN: {
    name: 'Finance Admin',
    description: 'Cross-operator invoices, payments, and outstanding balances.',
    scope: 'PLATFORM',
  },
  COMPANY_ADMIN: {
    name: 'Company Admin',
    description: 'Administrator of a transport operator organization.',
    scope: 'OPERATOR',
  },
  LOGISTICS_MANAGER: {
    name: 'Logistics Manager',
    description: 'Shipments, fleet, drivers, routes, and assignment.',
    scope: 'OPERATOR',
  },
  FINANCE_OFFICER: {
    name: 'Finance Officer',
    description: 'Operator invoices, payments, and financial documents.',
    scope: 'OPERATOR',
  },
  DRIVER: {
    name: 'Driver',
    description: 'Assigned trips, status updates, proof of delivery, and location.',
    scope: 'OPERATOR',
  },
  CUSTOMER_ADMIN: {
    name: 'Customer Admin',
    description: 'Manages a customer organization, its users, and its freight.',
    scope: 'CUSTOMER',
  },
  CUSTOMER_USER: {
    name: 'Customer User',
    description: 'Creates and tracks shipments and views documents and invoices.',
    scope: 'CUSTOMER',
  },
};

export const ROLE_PERMISSIONS: Record<RoleCode, readonly PermissionCode[]> = {
  SUPER_ADMIN: PERMISSIONS,
  OPERATIONS_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'org.settings',
    'pod.manage',
    'pod.read',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.manage',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
    'tracking.manage',
    'tracking.read',
    'tracking.submit_location',
    'tracking.update_location',
    'tracking.view_history',
    'tracking.view_live',
    'users.manage',
    'invoices.read',
    'payments.read',
    'finance.read',
    'notification_delivery.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notification_templates.manage',
    'notification_templates.read',
    'notifications.manage',
    'notifications.read',
    'notifications.retry',
    'search.read',
    'users.read',
  ],
  FINANCE_ADMIN: [
    'audit.read',
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'dispatch.read',
    'documents.read',
    'driver_documents.read',
    'drivers.read',
    'invoices.cancel',
    'invoices.create',
    'invoices.issue',
    'invoices.manage',
    'invoices.read',
    'invoices.update',
    'payments.create',
    'payments.manage',
    'payments.read',
    'payments.record',
    'payments.refund',
    'payments.update',
    'finance.manage',
    'finance.read',
    'routes.read',
    'routes.view_history',
    'shipments.read',
    'shipments.view_history',
    'tracking.read',
    'tracking.view_history',
    'vehicle_documents.read',
    'vehicles.read',
    'notification_delivery.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'search.read',
  ],
  COMPANY_ADMIN: [
    'countries.read',
    'customers.create',
    'customers.delete',
    'customers.manage',
    'customers.read',
    'customers.update',
    'dashboard.finance',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'invoices.cancel',
    'invoices.create',
    'invoices.issue',
    'invoices.manage',
    'invoices.read',
    'invoices.update',
    'finance.manage',
    'finance.read',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'org.settings',
    'pod.create',
    'pod.manage',
    'pod.read',
    'payments.create',
    'payments.manage',
    'payments.read',
    'payments.record',
    'payments.refund',
    'payments.update',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.manage',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
    'tracking.manage',
    'tracking.read',
    'tracking.submit_location',
    'tracking.update_location',
    'tracking.view_history',
    'tracking.view_live',
    'users.manage',
    'notification_delivery.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notification_templates.manage',
    'notification_templates.read',
    'notifications.manage',
    'notifications.read',
    'notifications.retry',
    'search.read',
    'users.read',
  ],
  LOGISTICS_MANAGER: [
    'countries.read',
    'customers.create',
    'customers.read',
    'customers.update',
    'dashboard.operations',
    'dispatch.dispatch',
    'dispatch.manage',
    'dispatch.read',
    'documents.read',
    'driver_documents.create',
    'driver_documents.delete',
    'driver_documents.manage',
    'driver_documents.read',
    'driver_documents.update',
    'drivers.create',
    'drivers.delete',
    'drivers.manage',
    'drivers.read',
    'drivers.status_update',
    'drivers.update',
    'fleet.manage',
    'routes.create',
    'routes.delete',
    'routes.dispatch',
    'routes.manage',
    'routes.read',
    'routes.status_update',
    'routes.update',
    'routes.view_history',
    'vehicle_documents.create',
    'vehicle_documents.delete',
    'vehicle_documents.manage',
    'vehicle_documents.read',
    'vehicle_documents.update',
    'vehicles.create',
    'vehicles.delete',
    'vehicles.manage',
    'vehicles.read',
    'vehicles.status_update',
    'vehicles.update',
    'shipments.assign',
    'shipments.create',
    'shipments.delete',
    'shipments.read',
    'shipments.update',
    'shipments.update_status',
    'shipments.view_history',
    'tracking.manage',
    'tracking.read',
    'tracking.submit_location',
    'tracking.update_location',
    'tracking.view_history',
    'tracking.view_live',
    'invoices.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'pod.manage',
    'pod.read',
    'search.read',
  ],
  FINANCE_OFFICER: [
    'countries.read',
    'customers.read',
    'dashboard.finance',
    'dispatch.read',
    'documents.read',
    'driver_documents.read',
    'drivers.read',
    'invoices.cancel',
    'invoices.create',
    'invoices.issue',
    'invoices.manage',
    'invoices.read',
    'invoices.update',
    'payments.create',
    'payments.manage',
    'payments.read',
    'payments.record',
    'payments.refund',
    'payments.update',
    'finance.manage',
    'finance.read',
    'routes.read',
    'routes.view_history',
    'shipments.read',
    'shipments.view_history',
    'tracking.read',
    'tracking.view_history',
    'vehicle_documents.read',
    'vehicles.read',
    'notification_delivery.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'search.read',
  ],
  DRIVER: [
    'countries.read',
    'documents.read',
    'shipments.read',
    'shipments.update_status',
    'shipments.upload_pod',
    'shipments.view_history',
    'tracking.read',
    'tracking.submit_location',
    'tracking.update_location',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'pod.create',
    'pod.read',
    'search.read',
  ],
  CUSTOMER_ADMIN: [
    'countries.read',
    'documents.read',
    'invoices.read',
    'payments.read',
    'org.settings',
    'shipments.create',
    'shipments.read',
    'shipments.view_history',
    'tracking.read',
    'users.manage',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'search.read',
    'users.read',
  ],
  CUSTOMER_USER: [
    'countries.read',
    'documents.read',
    'shipments.create',
    'shipments.read',
    'shipments.view_history',
    'tracking.read',
    'invoices.read',
    'payments.read',
    'notification_preferences.read',
    'notification_preferences.update',
    'notifications.read',
    'search.read',
  ],
};

export function normalizePermission(code: string): string {
  return code.replaceAll(':', '.');
}

export function can(granted: readonly string[] | undefined, permission: string) {
  if (!granted?.length) {
    return false;
  }
  const needed = normalizePermission(permission);
  if (granted.includes(needed)) {
    return true;
  }
  const resource = needed.split('.')[0];
  return Boolean(resource && granted.includes(`${resource}.manage`));
}

export function canAny(granted: readonly string[] | undefined, ...permissions: string[]) {
  return permissions.some((permission) => can(granted, permission));
}

export function canAll(granted: readonly string[] | undefined, ...permissions: string[]) {
  return permissions.every((permission) => can(granted, permission));
}

export function canReadPod(granted: readonly string[] | undefined) {
  return canAny(granted, 'pod.read', 'pod.manage', 'shipments.upload_pod');
}

export function canCreatePod(granted: readonly string[] | undefined) {
  return canAny(granted, 'pod.create', 'pod.manage', 'shipments.upload_pod');
}

export function canManagePod(granted: readonly string[] | undefined) {
  return can(granted, 'pod.manage');
}

export function canSearch(granted: readonly string[] | undefined) {
  return can(granted, 'search.read');
}

export function canReadUsers(granted: readonly string[] | undefined) {
  return canAny(granted, 'users.read', 'users.manage');
}

export function canManageUsers(granted: readonly string[] | undefined) {
  return can(granted, 'users.manage');
}

export function canReadOperationsDashboard(granted: readonly string[] | undefined) {
  return can(granted, 'dashboard.operations');
}

export function canReadFinanceDashboard(granted: readonly string[] | undefined) {
  return can(granted, 'dashboard.finance');
}

export function canManageOrgSettings(granted: readonly string[] | undefined) {
  return can(granted, 'org.settings');
}

export function canReadAudit(granted: readonly string[] | undefined) {
  return can(granted, 'audit.read');
}
